import { CardTemplate } from '../types';
import { CR80_WIDTH_MM, CR80_HEIGHT_MM } from './units';

/**
 * Generate SVG Data URL background for templates
 */
function createNationalIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1011" height="638" viewBox="0 0 1011 638">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#f8fafc"/>
        <stop offset="100%" stop-color="#e2e8f0"/>
      </linearGradient>
      <linearGradient id="header" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#1e3a8a"/>
        <stop offset="100%" stop-color="#3b82f6"/>
      </linearGradient>
      <linearGradient id="gold" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#d97706"/>
        <stop offset="100%" stop-color="#fbbf24"/>
      </linearGradient>
    </defs>
    <rect width="1011" height="638" fill="url(#bg)"/>
    <!-- Top Header Ribbon -->
    <path d="M0 0 L1011 0 L1011 110 L0 140 Z" fill="url(#header)"/>
    <path d="M0 140 L1011 110 L1011 120 L0 150 Z" fill="url(#gold)"/>
    <!-- Security Waves -->
    <path d="M 0 300 Q 250 200 500 300 T 1000 300" stroke="rgba(59,130,246,0.15)" stroke-width="4" fill="none"/>
    <path d="M 0 340 Q 250 240 500 340 T 1000 340" stroke="rgba(217,119,6,0.15)" stroke-width="3" fill="none"/>
    <path d="M 0 380 Q 250 280 500 380 T 1000 380" stroke="rgba(59,130,246,0.12)" stroke-width="2" fill="none"/>
    <!-- Bottom Bar -->
    <rect y="608" width="1011" height="30" fill="#1e3a8a"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function createNationalIdBackBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1011" height="638" viewBox="0 0 1011 638">
    <defs>
      <linearGradient id="bg_back" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#f8fafc"/>
        <stop offset="100%" stop-color="#f1f5f9"/>
      </linearGradient>
      <linearGradient id="header_back" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#1e3a8a"/>
        <stop offset="100%" stop-color="#2563eb"/>
      </linearGradient>
    </defs>
    <rect width="1011" height="638" fill="url(#bg_back)"/>
    <!-- Top banner stripe -->
    <rect x="0" y="0" width="1011" height="42" fill="url(#header_back)"/>
    <rect x="0" y="42" width="1011" height="6" fill="#d97706"/>
    <!-- Guilloche Security Pattern -->
    <path d="M 0 150 Q 250 120 500 150 T 1000 150" stroke="rgba(37,99,235,0.08)" stroke-width="2" fill="none"/>
    <path d="M 0 200 Q 250 170 500 200 T 1000 200" stroke="rgba(217,119,6,0.08)" stroke-width="2" fill="none"/>
    <path d="M 0 250 Q 250 220 500 250 T 1000 250" stroke="rgba(37,99,235,0.06)" stroke-width="1.5" fill="none"/>
    <!-- Microprint line decoration -->
    <line x1="40" y1="360" x2="971" y2="360" stroke="#cbd5e1" stroke-width="1" stroke-dasharray="4 2"/>
    <!-- Bottom Magnetic Zone -->
    <rect x="0" y="520" width="1011" height="118" fill="#e2e8f0" stroke="#cbd5e1" stroke-width="1"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function createCorporateIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="638" height="1011" viewBox="0 0 638 1011">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#0f172a"/>
        <stop offset="100%" stop-color="#1e293b"/>
      </linearGradient>
      <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#06b6d4"/>
        <stop offset="100%" stop-color="#3b82f6"/>
      </linearGradient>
    </defs>
    <rect width="638" height="1011" fill="url(#bg)"/>
    <path d="M -100 0 L 738 0 L 638 280 L -100 200 Z" fill="url(#accent)"/>
    <circle cx="319" cy="240" r="100" fill="#0f172a" stroke="#06b6d4" stroke-width="4"/>
    <rect y="980" width="638" height="31" fill="#06b6d4"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function createStudentIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1011" height="638" viewBox="0 0 1011 638">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#fff1f2"/>
        <stop offset="100%" stop-color="#ffe4e6"/>
      </linearGradient>
      <linearGradient id="emerald" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#047857"/>
        <stop offset="100%" stop-color="#10b981"/>
      </linearGradient>
    </defs>
    <rect width="1011" height="638" fill="url(#bg)"/>
    <rect width="1011" height="120" fill="url(#emerald)"/>
    <rect y="120" width="1011" height="8" fill="#f59e0b"/>
    <circle cx="880" cy="300" r="220" fill="rgba(16,185,129,0.05)"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

export const SAMPLE_TEMPLATES: CardTemplate[] = [
  {
    id: 'sample_national_id',
    templateName: 'National ID Card (Landscape)',
    cardType: 'National ID',
    side: 'Front Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createNationalIdBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [
      { id: 'g1', type: 'vertical', position: 10, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g2', type: 'vertical', position: 35, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g3', type: 'horizontal', position: 12, color: '#3b82f6', locked: true, hidden: false },
    ],
    layers: [
      // Title Header
      {
        id: 'header_title',
        name: 'Header Title',
        type: 'text',
        x: 6,
        y: 2.5,
        width: 74,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'REPUBLIC IDENTITY CARD',
        fontFamily: 'Helvetica',
        fontSize: 3.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.2,
        lineHeight: 1.1,
      },
      {
        id: 'header_sub',
        name: 'Header Subtitle',
        type: 'text',
        x: 6,
        y: 7.5,
        width: 74,
        height: 4,
        rotation: 0,
        opacity: 0.9,
        locked: true,
        hidden: false,
        text: 'NATIONAL IDENTIFICATION AUTHORITY',
        fontFamily: 'Helvetica',
        fontSize: 2.2,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#FDE68A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // Photo Placeholder
      {
        id: 'photo_holder',
        name: 'Holder Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 6,
        y: 16,
        width: 25,
        height: 32,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#1e3a8a',
        backgroundColor: '#f1f5f9',
      },
      // Field Labels & Variables
      {
        id: 'lbl_surname',
        name: 'Surname Label',
        type: 'text',
        x: 34,
        y: 16,
        width: 45,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SURNAME / NOM',
        fontFamily: 'Helvetica',
        fontSize: 1.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_last_name',
        name: 'Last Name Var',
        type: 'text',
        x: 34,
        y: 19,
        width: 45,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{last_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_given_name',
        name: 'Given Name Label',
        type: 'text',
        x: 34,
        y: 23.5,
        width: 45,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'GIVEN NAMES / PRÉNOMS',
        fontFamily: 'Helvetica',
        fontSize: 1.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_first_name',
        name: 'First Name Var',
        type: 'text',
        x: 34,
        y: 26.5,
        width: 45,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_dob',
        name: 'DOB Label',
        type: 'text',
        x: 34,
        y: 31.5,
        width: 22,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'DATE OF BIRTH',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_dob',
        name: 'DOB Var',
        type: 'text',
        x: 34,
        y: 34,
        width: 22,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{dob}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_gender',
        name: 'Gender Label',
        type: 'text',
        x: 58,
        y: 31.5,
        width: 15,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SEX',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_gender',
        name: 'Gender Var',
        type: 'text',
        x: 58,
        y: 34,
        width: 15,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{gender}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_id_no',
        name: 'ID No Label',
        type: 'text',
        x: 34,
        y: 38.5,
        width: 45,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NATIONAL ID NO.',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_id_number',
        name: 'ID Number Var',
        type: 'text',
        x: 34,
        y: 41,
        width: 45,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{id_number}}',
        fontFamily: 'Helvetica',
        fontSize: 3.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#1E3A8A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // QR Code
      {
        id: 'qr_layer',
        name: 'Verification QR',
        type: 'qrcode',
        data: 'ID:{{id_number}}|NAME:{{first_name}} {{last_name}}',
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        x: 70,
        y: 15,
        width: 12,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
      // Barcode at bottom
      {
        id: 'barcode_layer',
        name: 'ID Barcode',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{id_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 34,
        y: 45.5,
        width: 45,
        height: 6.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_corporate_badge',
    templateName: 'Corporate Employee Badge (Portrait)',
    cardType: 'Employee ID',
    side: 'Front Side',
    cardWidth: CR80_HEIGHT_MM, // Portrait orientation
    cardHeight: CR80_WIDTH_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'portrait',
    background: {
      type: 'image',
      src: createCorporateIdBg(),
      originalWidthPx: 638,
      originalHeightPx: 1011,
    },
    guides: [],
    layers: [
      {
        id: 'corp_name',
        name: 'Company Name',
        type: 'text',
        x: 4,
        y: 4,
        width: 46,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NEXUS TECH CORP',
        fontFamily: 'Arial',
        fontSize: 3.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'center',
        letterSpacing: 0.2,
        lineHeight: 1.0,
      },
      {
        id: 'emp_photo',
        name: 'Employee Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 12,
        y: 14,
        width: 30,
        height: 38,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#06b6d4',
        backgroundColor: '#1e293b',
      },
      {
        id: 'emp_name_var',
        name: 'Full Name',
        type: 'text',
        x: 2,
        y: 54,
        width: 50,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}} {{last_name}}',
        fontFamily: 'Arial',
        fontSize: 3.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'center',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'emp_role_var',
        name: 'Designation / Role',
        type: 'text',
        x: 2,
        y: 59.5,
        width: 50,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{role}}',
        fontFamily: 'Arial',
        fontSize: 2.8,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#06B6D4',
        align: 'center',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'emp_id_lbl',
        name: 'EMP ID Label',
        type: 'text',
        x: 4,
        y: 65,
        width: 46,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'EMP ID: {{id_number}}',
        fontFamily: 'Arial',
        fontSize: 2.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#94A3B8',
        align: 'center',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'qr_code_emp',
        name: 'Security QR',
        type: 'qrcode',
        data: 'EMPLOYEE: {{first_name}} {{last_name}} | ID: {{id_number}}',
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        x: 18,
        y: 69,
        width: 18,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_student_id',
    templateName: 'University Student Pass',
    cardType: 'Student ID',
    side: 'Front Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createStudentIdBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [],
    layers: [
      {
        id: 'uni_title',
        name: 'University Title',
        type: 'text',
        x: 6,
        y: 3,
        width: 74,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'ST. STANFORD UNIVERSITY',
        fontFamily: 'Times New Roman',
        fontSize: 4.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'uni_sub',
        name: 'Card Title',
        type: 'text',
        x: 6,
        y: 7.5,
        width: 74,
        height: 3,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        text: 'STUDENT IDENTIFICATION CARD',
        fontFamily: 'Helvetica',
        fontSize: 2.0,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#F59E0B',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      {
        id: 'student_photo',
        name: 'Student Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 6,
        y: 15,
        width: 24,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#047857',
        backgroundColor: '#ffffff',
      },
      {
        id: 'student_name',
        name: 'Name Var',
        type: 'text',
        x: 32,
        y: 15,
        width: 48,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}} {{last_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#064E3B',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      {
        id: 'dept_label',
        name: 'Dept Var',
        type: 'text',
        x: 32,
        y: 21,
        width: 48,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'Dept: {{department}}',
        fontFamily: 'Helvetica',
        fontSize: 2.4,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#334155',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'reg_no',
        name: 'Reg No',
        type: 'text',
        x: 32,
        y: 25.5,
        width: 48,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'REG NO: {{id_number}}',
        fontFamily: 'Helvetica',
        fontSize: 2.4,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#047857',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'expiry',
        name: 'Valid Until',
        type: 'text',
        x: 32,
        y: 30,
        width: 48,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'VALID UNTIL: {{card_expiry}}',
        fontFamily: 'Helvetica',
        fontSize: 2.0,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'student_barcode',
        name: 'Barcode',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{id_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 32,
        y: 35,
        width: 46,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_tanzania_nida_front',
    templateName: 'Tanzania National ID (NIDA Front Side)',
    cardType: 'National ID',
    side: 'Front Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createNationalIdBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [
      { id: 'g1', type: 'vertical', position: 8, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g2', type: 'vertical', position: 32, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g3', type: 'horizontal', position: 12, color: '#3b82f6', locked: true, hidden: false },
    ],
    layers: [
      // Title Header
      {
        id: 'nida_header_title',
        name: 'Header Country',
        type: 'text',
        x: 6,
        y: 2.2,
        width: 74,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'JAMHURI YA MUUNGANO WA TANZANIA',
        fontFamily: 'Archivo Black',
        fontSize: 3.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'nida_header_sub',
        name: 'Header Authority',
        type: 'text',
        x: 6,
        y: 7.2,
        width: 74,
        height: 3.5,
        rotation: 0,
        opacity: 0.95,
        locked: true,
        hidden: false,
        text: 'NATIONAL IDENTIFICATION AUTHORITY (NIDA)',
        fontFamily: 'Helvetica',
        fontSize: 2.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FDE68A',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      // Photo Placeholder (PHOTO)
      {
        id: 'photo_holder',
        name: 'Holder Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 6,
        y: 14,
        width: 23,
        height: 29,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#1e3a8a',
        backgroundColor: '#f1f5f9',
      },
      // Signature Placeholder (SIGNATURE)
      {
        id: 'sig_holder',
        name: 'Holder Signature',
        type: 'placeholder',
        placeholderKey: 'signature',
        label: 'Signature',
        placeholderType: 'signature',
        x: 6,
        y: 44,
        width: 23,
        height: 7.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#94a3b8',
        backgroundColor: '#ffffff',
      },
      // Surname / Last Name (LAST_NAME)
      {
        id: 'lbl_surname',
        name: 'Surname Label',
        type: 'text',
        x: 31,
        y: 13.5,
        width: 48,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SURNAME / JINA LA UKOO',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_last_name',
        name: 'Last Name Var',
        type: 'text',
        x: 31,
        y: 15.8,
        width: 48,
        height: 3.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{last_name}}',
        fontFamily: 'Archivo Black',
        fontSize: 3.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // First Name (FIRST_NAME)
      {
        id: 'lbl_first_name',
        name: 'First Name Label',
        type: 'text',
        x: 31,
        y: 20.0,
        width: 25,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'FIRST NAME / JINA LA KWANZA',
        fontFamily: 'Helvetica',
        fontSize: 1.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_first_name',
        name: 'First Name Var',
        type: 'text',
        x: 31,
        y: 22.3,
        width: 25,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}}',
        fontFamily: 'Helvetica',
        fontSize: 2.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      // Middle Name (MIDDLE_NAME)
      {
        id: 'lbl_middle_name',
        name: 'Middle Name Label',
        type: 'text',
        x: 58,
        y: 20.0,
        width: 22,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'MIDDLE NAME / LA KATI',
        fontFamily: 'Helvetica',
        fontSize: 1.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_middle_name',
        name: 'Middle Name Var',
        type: 'text',
        x: 58,
        y: 22.3,
        width: 22,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{middle_name}}',
        fontFamily: 'Helvetica',
        fontSize: 2.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      // Date of Birth (DOB)
      {
        id: 'lbl_dob',
        name: 'DOB Label',
        type: 'text',
        x: 31,
        y: 26.5,
        width: 25,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'DATE OF BIRTH',
        fontFamily: 'Helvetica',
        fontSize: 1.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_dob',
        name: 'DOB Var',
        type: 'text',
        x: 31,
        y: 28.8,
        width: 25,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{dob}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      // Gender (GENDER)
      {
        id: 'lbl_gender',
        name: 'Gender Label',
        type: 'text',
        x: 58,
        y: 26.5,
        width: 15,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SEX / JINSIA',
        fontFamily: 'Helvetica',
        fontSize: 1.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_gender',
        name: 'Gender Var',
        type: 'text',
        x: 58,
        y: 28.8,
        width: 15,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{gender}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      // NIDA Number (NIDA_NUMBER)
      {
        id: 'lbl_nida_no',
        name: 'NIDA No Label',
        type: 'text',
        x: 31,
        y: 33.2,
        width: 50,
        height: 2.4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NATIONAL ID NO. / NAMBARI YA NIDA',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_nida_number',
        name: 'NIDA Number Var',
        type: 'text',
        x: 31,
        y: 35.8,
        width: 50,
        height: 4.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{nida_number}}',
        fontFamily: 'Archivo Black',
        fontSize: 3.1,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#1E3A8A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // Security QR Code
      {
        id: 'qr_nida',
        name: 'NIDA Verification QR',
        type: 'qrcode',
        data: 'NIDA:{{nida_number}}|NAME:{{first_name}} {{middle_name}} {{last_name}}',
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        x: 69,
        y: 13.5,
        width: 12,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
      // Barcode at bottom
      {
        id: 'barcode_nida',
        name: 'NIDA Barcode',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{nida_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 31,
        y: 43.5,
        width: 48,
        height: 8.0,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_tanzania_nida_back',
    templateName: 'Tanzania National ID (NIDA Back Side)',
    cardType: 'National ID',
    side: 'Back Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createNationalIdBackBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [
      { id: 'gb1', type: 'vertical', position: 10, color: '#3b82f6', locked: true, hidden: false },
      { id: 'gb2', type: 'horizontal', position: 10, color: '#3b82f6', locked: true, hidden: false },
    ],
    layers: [
      // Top statutory banner
      {
        id: 'back_header_title',
        name: 'Header Statutory',
        type: 'text',
        x: 6,
        y: 2.2,
        width: 74,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'JAMHURI YA MUUNGANO WA TANZANIA • NIDA',
        fontFamily: 'Archivo Black',
        fontSize: 2.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // Legal ownership text Swahili
      {
        id: 'legal_text_swahili',
        name: 'Legal Text Swahili',
        type: 'text',
        x: 6,
        y: 8.5,
        width: 74,
        height: 6.5,
        rotation: 0,
        opacity: 0.95,
        locked: true,
        hidden: false,
        text: 'Kitambulisho hiki ni mali ya Serikali ya Jamhuri ya Muungano wa Tanzania. Kikipotea au kuokotwa kirudishwe katika Ofisi ya NIDA au Kituo cha Polisi kilicho karibu.',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#334155',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.25,
      },
      // Legal ownership text English
      {
        id: 'legal_text_english',
        name: 'Legal Text English',
        type: 'text',
        x: 6,
        y: 15.5,
        width: 74,
        height: 5.5,
        rotation: 0,
        opacity: 0.9,
        locked: true,
        hidden: false,
        text: 'This card is the property of the Government of the United Republic of Tanzania. If found, please return to NIDA or the nearest Police Station.',
        fontFamily: 'Helvetica',
        fontSize: 1.5,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#475569',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.25,
      },
      // Issuing Authority Office
      {
        id: 'issuing_authority_address',
        name: 'Issuing Office',
        type: 'text',
        x: 6,
        y: 22.0,
        width: 74,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'NATIONAL IDENTIFICATION AUTHORITY (NIDA) • P.O. BOX 11492, DAR ES SALAAM',
        fontFamily: 'Helvetica',
        fontSize: 1.7,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#1E3A8A',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      // NIDA Number Label
      {
        id: 'lbl_nida_back',
        name: 'NIDA Label (Back)',
        type: 'text',
        x: 20,
        y: 26.5,
        width: 46,
        height: 2.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NAMBARI YA KITAMBULISHO / ID NUMBER',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'center',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      // NIDA Number Variable
      {
        id: 'var_nida_number_back',
        name: 'NIDA Number (Back)',
        type: 'text',
        x: 18,
        y: 29.0,
        width: 50,
        height: 4.2,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{nida_number}}',
        fontFamily: 'Archivo Black',
        fontSize: 3.1,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'center',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // Synchronized Barcode
      {
        id: 'barcode_nida_back',
        name: 'NIDA Barcode (Back)',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{nida_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 18,
        y: 34.0,
        width: 50,
        height: 9.0,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
      // MRZ Machine Readable Lines (Untouched legal bottom lines)
      {
        id: 'mrz_line1',
        name: 'MRZ Line 1',
        type: 'text',
        x: 5,
        y: 44.5,
        width: 76,
        height: 3.2,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'I<TZA0000000000<<<<<<<<<<<<<<<',
        fontFamily: 'Courier New',
        fontSize: 2.3,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#334155',
        align: 'left',
        letterSpacing: 0.2,
        lineHeight: 1.0,
      },
      {
        id: 'mrz_line2',
        name: 'MRZ Line 2',
        type: 'text',
        x: 5,
        y: 48.0,
        width: 76,
        height: 3.2,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: '9803010M<<<<<<<TZA<<<<<<<<<<<2',
        fontFamily: 'Courier New',
        fontSize: 2.3,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#334155',
        align: 'left',
        letterSpacing: 0.2,
        lineHeight: 1.0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

