import { CardTemplate } from '../types';
import { CR80_WIDTH_MM, CR80_HEIGHT_MM } from './units';

/**
 * Generate SVG Data URL background for templates
 */
function createNationalIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1011" height="638" viewBox="0 0 1011 638">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#f8fafc"/>
        <stop offset="100%" stop-color="#e2e8f0"/>
      </linearGradient>
      <linearGradient id="header" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#1e3a8a"/>
        <stop offset="100%" stop-color="#3b82f6"/>
      </linearGradient>
      <linearGradient id="gold" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#d97706"/>
        <stop offset="100%" stop-color="#fbbf24"/>
      </linearGradient>
    </defs>
    <rect width="1011" height="638" fill="url(#bg)"/>
    <!-- Top Header Ribbon -->
    <path d="M0 0 L1011 0 L1011 110 L0 140 Z" fill="url(#header)"/>
    <path d="M0 140 L1011 110 L1011 120 L0 150 Z" fill="url(#gold)"/>
    <!-- Security Waves -->
    <path d="M 0 300 Q 250 200 500 300 T 1000 300" stroke="rgba(59,130,246,0.15)" stroke-width="4" fill="none"/>
    <path d="M 0 340 Q 250 240 500 340 T 1000 340" stroke="rgba(217,119,6,0.15)" stroke-width="3" fill="none"/>
    <path d="M 0 380 Q 250 280 500 380 T 1000 380" stroke="rgba(59,130,246,0.12)" stroke-width="2" fill="none"/>
    <!-- Bottom Bar -->
    <rect y="608" width="1011" height="30" fill="#1e3a8a"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function createCorporateIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="638" height="1011" viewBox="0 0 638 1011">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#0f172a"/>
        <stop offset="100%" stop-color="#1e293b"/>
      </linearGradient>
      <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#06b6d4"/>
        <stop offset="100%" stop-color="#3b82f6"/>
      </linearGradient>
    </defs>
    <rect width="638" height="1011" fill="url(#bg)"/>
    <path d="M -100 0 L 738 0 L 638 280 L -100 200 Z" fill="url(#accent)"/>
    <circle cx="319" cy="240" r="100" fill="#0f172a" stroke="#06b6d4" stroke-width="4"/>
    <rect y="980" width="638" height="31" fill="#06b6d4"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function createStudentIdBg(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1011" height="638" viewBox="0 0 1011 638">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#fff1f2"/>
        <stop offset="100%" stop-color="#ffe4e6"/>
      </linearGradient>
      <linearGradient id="emerald" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#047857"/>
        <stop offset="100%" stop-color="#10b981"/>
      </linearGradient>
    </defs>
    <rect width="1011" height="638" fill="url(#bg)"/>
    <rect width="1011" height="120" fill="url(#emerald)"/>
    <rect y="120" width="1011" height="8" fill="#f59e0b"/>
    <circle cx="880" cy="300" r="220" fill="rgba(16,185,129,0.05)"/>
  </svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

export const SAMPLE_TEMPLATES: CardTemplate[] = [
  {
    id: 'sample_national_id',
    templateName: 'National ID Card (Landscape)',
    cardType: 'National ID',
    side: 'Front Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createNationalIdBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [
      { id: 'g1', type: 'vertical', position: 10, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g2', type: 'vertical', position: 35, color: '#3b82f6', locked: true, hidden: false },
      { id: 'g3', type: 'horizontal', position: 12, color: '#3b82f6', locked: true, hidden: false },
    ],
    layers: [
      // Title Header
      {
        id: 'header_title',
        name: 'Header Title',
        type: 'text',
        x: 6,
        y: 2.5,
        width: 74,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        text: 'REPUBLIC IDENTITY CARD',
        fontFamily: 'Helvetica',
        fontSize: 3.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.2,
        lineHeight: 1.1,
      },
      {
        id: 'header_sub',
        name: 'Header Subtitle',
        type: 'text',
        x: 6,
        y: 7.5,
        width: 74,
        height: 4,
        rotation: 0,
        opacity: 0.9,
        locked: true,
        hidden: false,
        text: 'NATIONAL IDENTIFICATION AUTHORITY',
        fontFamily: 'Helvetica',
        fontSize: 2.2,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#FDE68A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // Photo Placeholder
      {
        id: 'photo_holder',
        name: 'Holder Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 6,
        y: 16,
        width: 25,
        height: 32,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#1e3a8a',
        backgroundColor: '#f1f5f9',
      },
      // Field Labels & Variables
      {
        id: 'lbl_surname',
        name: 'Surname Label',
        type: 'text',
        x: 34,
        y: 16,
        width: 45,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SURNAME / NOM',
        fontFamily: 'Helvetica',
        fontSize: 1.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_last_name',
        name: 'Last Name Var',
        type: 'text',
        x: 34,
        y: 19,
        width: 45,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{last_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_given_name',
        name: 'Given Name Label',
        type: 'text',
        x: 34,
        y: 23.5,
        width: 45,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'GIVEN NAMES / PRÉNOMS',
        fontFamily: 'Helvetica',
        fontSize: 1.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_first_name',
        name: 'First Name Var',
        type: 'text',
        x: 34,
        y: 26.5,
        width: 45,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_dob',
        name: 'DOB Label',
        type: 'text',
        x: 34,
        y: 31.5,
        width: 22,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'DATE OF BIRTH',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_dob',
        name: 'DOB Var',
        type: 'text',
        x: 34,
        y: 34,
        width: 22,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{dob}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_gender',
        name: 'Gender Label',
        type: 'text',
        x: 58,
        y: 31.5,
        width: 15,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'SEX',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_gender',
        name: 'Gender Var',
        type: 'text',
        x: 58,
        y: 34,
        width: 15,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{gender}}',
        fontFamily: 'Helvetica',
        fontSize: 2.6,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#0F172A',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'lbl_id_no',
        name: 'ID No Label',
        type: 'text',
        x: 34,
        y: 38.5,
        width: 45,
        height: 2.8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NATIONAL ID NO.',
        fontFamily: 'Helvetica',
        fontSize: 1.6,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'var_id_number',
        name: 'ID Number Var',
        type: 'text',
        x: 34,
        y: 41,
        width: 45,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{id_number}}',
        fontFamily: 'Helvetica',
        fontSize: 3.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#1E3A8A',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      // QR Code
      {
        id: 'qr_layer',
        name: 'Verification QR',
        type: 'qrcode',
        data: 'ID:{{id_number}}|NAME:{{first_name}} {{last_name}}',
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        x: 70,
        y: 15,
        width: 12,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
      // Barcode at bottom
      {
        id: 'barcode_layer',
        name: 'ID Barcode',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{id_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 34,
        y: 45.5,
        width: 45,
        height: 6.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_corporate_badge',
    templateName: 'Corporate Employee Badge (Portrait)',
    cardType: 'Employee ID',
    side: 'Front Side',
    cardWidth: CR80_HEIGHT_MM, // Portrait orientation
    cardHeight: CR80_WIDTH_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'portrait',
    background: {
      type: 'image',
      src: createCorporateIdBg(),
      originalWidthPx: 638,
      originalHeightPx: 1011,
    },
    guides: [],
    layers: [
      {
        id: 'corp_name',
        name: 'Company Name',
        type: 'text',
        x: 4,
        y: 4,
        width: 46,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'NEXUS TECH CORP',
        fontFamily: 'Arial',
        fontSize: 3.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'center',
        letterSpacing: 0.2,
        lineHeight: 1.0,
      },
      {
        id: 'emp_photo',
        name: 'Employee Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 12,
        y: 14,
        width: 30,
        height: 38,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#06b6d4',
        backgroundColor: '#1e293b',
      },
      {
        id: 'emp_name_var',
        name: 'Full Name',
        type: 'text',
        x: 2,
        y: 54,
        width: 50,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}} {{last_name}}',
        fontFamily: 'Arial',
        fontSize: 3.8,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'center',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'emp_role_var',
        name: 'Designation / Role',
        type: 'text',
        x: 2,
        y: 59.5,
        width: 50,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{role}}',
        fontFamily: 'Arial',
        fontSize: 2.8,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#06B6D4',
        align: 'center',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'emp_id_lbl',
        name: 'EMP ID Label',
        type: 'text',
        x: 4,
        y: 65,
        width: 46,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'EMP ID: {{id_number}}',
        fontFamily: 'Arial',
        fontSize: 2.2,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#94A3B8',
        align: 'center',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'qr_code_emp',
        name: 'Security QR',
        type: 'qrcode',
        data: 'EMPLOYEE: {{first_name}} {{last_name}} | ID: {{id_number}}',
        colorDark: '#0f172a',
        colorLight: '#ffffff',
        x: 18,
        y: 69,
        width: 18,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample_student_id',
    templateName: 'University Student Pass',
    cardType: 'Student ID',
    side: 'Front Side',
    cardWidth: CR80_WIDTH_MM,
    cardHeight: CR80_HEIGHT_MM,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    background: {
      type: 'image',
      src: createStudentIdBg(),
      originalWidthPx: 1011,
      originalHeightPx: 638,
    },
    guides: [],
    layers: [
      {
        id: 'uni_title',
        name: 'University Title',
        type: 'text',
        x: 6,
        y: 3,
        width: 74,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'ST. STANFORD UNIVERSITY',
        fontFamily: 'Times New Roman',
        fontSize: 4.0,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#FFFFFF',
        align: 'left',
        letterSpacing: 0.1,
        lineHeight: 1.0,
      },
      {
        id: 'uni_sub',
        name: 'Card Title',
        type: 'text',
        x: 6,
        y: 7.5,
        width: 74,
        height: 3,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        text: 'STUDENT IDENTIFICATION CARD',
        fontFamily: 'Helvetica',
        fontSize: 2.0,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#F59E0B',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      {
        id: 'student_photo',
        name: 'Student Photo',
        type: 'placeholder',
        placeholderKey: 'photo',
        label: 'Photo',
        placeholderType: 'photo',
        x: 6,
        y: 15,
        width: 24,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        borderColor: '#047857',
        backgroundColor: '#ffffff',
      },
      {
        id: 'student_name',
        name: 'Name Var',
        type: 'text',
        x: 32,
        y: 15,
        width: 48,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: '{{first_name}} {{last_name}}',
        fontFamily: 'Helvetica',
        fontSize: 3.5,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#064E3B',
        align: 'left',
        letterSpacing: 0.05,
        lineHeight: 1.0,
      },
      {
        id: 'dept_label',
        name: 'Dept Var',
        type: 'text',
        x: 32,
        y: 21,
        width: 48,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'Dept: {{department}}',
        fontFamily: 'Helvetica',
        fontSize: 2.4,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#334155',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'reg_no',
        name: 'Reg No',
        type: 'text',
        x: 32,
        y: 25.5,
        width: 48,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'REG NO: {{id_number}}',
        fontFamily: 'Helvetica',
        fontSize: 2.4,
        fontStyle: 'bold',
        textDecoration: 'none',
        color: '#047857',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'expiry',
        name: 'Valid Until',
        type: 'text',
        x: 32,
        y: 30,
        width: 48,
        height: 3,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        text: 'VALID UNTIL: {{card_expiry}}',
        fontFamily: 'Helvetica',
        fontSize: 2.0,
        fontStyle: 'normal',
        textDecoration: 'none',
        color: '#64748B',
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1.0,
      },
      {
        id: 'student_barcode',
        name: 'Barcode',
        type: 'barcode',
        barcodeType: 'Code128',
        data: '{{id_number}}',
        lineColor: '#000000',
        backgroundColor: '#ffffff',
        includeText: true,
        x: 32,
        y: 35,
        width: 46,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
